mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/admin/', admin.site.urls),
    path('exam/', include('quiz.urls')),
    path('', include('accounts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('roleplay/', include('roleplay.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.index, name='quiz'),
    path('<int:num>/', views.exam, name='exam'),
    path('<int:num>/results/', views.results, name='results'),
]

roleplay/urls.py
from django.urls import path
from django.urls import include
from . import views

#app_name = 'roleplay'

urlpatterns = [
    path('', views.index, name='roleplay'),
    path('<int:pk>', views.case, name='case'),
    path('<int:pk>/feedback', views.feedback, name='feedback'),
]

roleplay/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime

# Create your models here.
class Cluster(models.Model):
    title = models.CharField(max_length=100)

    def __str__(self):
        return self.title

class Event(models.Model):
    title = models.CharField(max_length=100)
    code = models.CharField(max_length=10)
    cluster = models.ForeignKey(Cluster, on_delete=models.CASCADE)
    team = models.BooleanField(default=False)  

    def __str__(self):
        return self.code

class Case(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    year = models.IntegerField(default=0)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    REGIONALS = 'R'
    PROVINCIALS = 'P'
    ICDC = 'I'
    LEVELS = [
        (REGIONALS, 'Regionals'),
        (PROVINCIALS, 'Provincials'),
        (ICDC, 'ICDC'),
    ]
    level = models.CharField(max_length=1, choices=LEVELS)

    def __str__(self):
        return self.title

class PI(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title

class CaseQuestion(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)

    def __str__(self):
        return self.title

class Submission(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE)
    student = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=datetime.now, blank=True)
    audio_file = models.FileField(upload_to="case/audio/")
    marked = models.BooleanField(default=False)
    feedback_strength = models.TextField(default='')
    feedback_improvement = models.TextField(default='')
    score = models.IntegerField(default=0)
    def __str__(self):
        return self.case.title+" ("+self.student.username+")"

roleplay/forms.py
from django import forms
from .models import Submission

class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = {'audio_file'}

roleplay/views.py
from django.shortcuts import render, redirect
from .models import Case, Submission
from .forms import SubmissionForm
from django.contrib.auth.decorators import login_required

@login_required(login_url='accounts:login')
def index(request):
    """
    Displays a list of roleplays
    """
    context = {}
    if request.user.profile.event is not None:
        context['cases'] = Case.objects.filter(event=request.user.profile.event)
    else:
        context['cases'] = Case.objects.all()
    return render(request, 'roleplay/index.html', context)

@login_required(login_url='accounts:login')
def case(request, pk):
    """
    Displays the content of a case
    """
    form = SubmissionForm()
    if request.method == 'POST':
        sub = Submission(student=request.user, case=Case.objects.get(pk=pk))
        form = SubmissionForm(request.POST, request.FILES, instance=sub)
        if form.is_valid():
            form.save()
        return redirect('roleplay')
    return render(request, 'roleplay/case.html', {'case':Case.objects.get(pk=pk), 'form':form, 'submissions':Submission.objects.filter(student=request.user).order_by('-date')})

@login_required(login_url='accounts:login')
def feedback(request, pk):
    """
    Displays the feedback from a user's submission
    """
    return render(request, 'roleplay/feedback.html', {'submission': Submission.objects.get(pk=pk)})

roleplay/templates/roleplay/case.html
{% extends 'base.html' %}
{% block content %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">{{case.title}} - {{case.year}} {{case.get_level_display}}</h6>
    </div>
    <div class="card-body">
        <!--<a href="{% url 'roleplay' %}" class="btn btn-link">Back to Case List</a>-->
        <p>{{case.description}}</p>
    </div>
</div>
<div class="card shadow mb-4">
    <a href="#pi" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="pi">
        <h6 class="m-0 font-weight-bold text-primary">Performance Indicators</h6>
    </a>
    <div class="collapse show" id="pi">
        <div class="card-body">
            <ul>
                {% for pi in case.pi_set.all %}
                    <li>{{pi.title}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<!--<div class="card shadow mb-4">
    <a href="#strengths" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="strengths">
        <h6 class="m-0 font-weight-bold text-primary">Case Situation</h6>
    </a>
    <div class="collapse show" id="strengths">
        <div class="card-body">
            <p>{{case.description}}</p>
        </div>
    </div>
</div>-->
<div class="card shadow mb-4">
    <a href="#caseq" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="caseq">
        <h6 class="m-0 font-weight-bold text-primary">Questions</h6>
    </a>
    <div class="collapse show" id="caseq">
        <div class="card-body">
            <ul>
                {% for question in case.casequestion_set.all %}
                    <li>{{question.title}}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
<div>
{% if submissions.count > 0 %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Submit</h6>
        </div>
        <div class="card-body">
            <form action='' method='POST' enctype='multipart/form-data'>
                {% csrf_token %}
                <!--{{form.as_p}}-->
                <input type="file" name="audio_file">
                <button type='submit' class="btn btn-primary">Submit</button>
            </form>
            <br>
            <div class="card shadow mb-4">
                <a href="#pastsub" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="pastsub">
                    <h6 class="m-0 font-weight-bold text-primary">Past Submissions</h6>
                </a>
                <div class="collapse" id="pastsub">
                    <div class="card-body">
                        <ul>
                            {% for submission in submissions %}
                                {% if submission.marked %}
                                    <p><a href="{% url 'feedback' pk=submission.id %}">{{submission.date}}</a></p>
                                {% else %}
                                    <p>{{submission.date}}</p>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

roleplay/templates/roleplay/feedback.html
{% extends 'base.html' %}
{% block content %}
<!-- Project Card Example -->
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Submission Info</h6>
    </div>
    <div class="card-body">
        <p>Case: <a href="{% url 'case' submission.case.pk %}">{{submission.case.title}}</a></p>
        <p>Event: {{submission.case.event.title}}</p>
        <p>Level: {{submission.case.get_level_display}}</p>
        <p>Time: {{submission.date}}</p>
        {% if submission.score > 0 %}
            <p>Score: {{submission.score}} / 100</p>
        {% endif %}
        <a href="{{submission.audio_file.url}}" target="blank" class="btn btn-primary btn-icon-split">
            <span class="icon text-white-50">
                <i class="fas fa-arrow-right"></i>
            </span>
            <span class="text">Replay Presentation</span>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-lg-6">
        <div class="card shadow mb-4">
            <a href="#strengths" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="strengths">
                <h6 class="m-0 font-weight-bold text-primary">Strengths</h6>
            </a>
            <div class="collapse show" id="strengths">
                <div class="card-body">
                    {{submission.feedback_strength}}
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <div class="card shadow mb-4">
            <a href="#improvement" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="improvement">
                <h6 class="m-0 font-weight-bold text-primary">Suggestions for Improvement</h6>
            </a>
            <div class="collapse show" id="improvement">
                <div class="card-body">
                    {{submission.feedback_improvement}}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

roleplay/templates/roleplay/index.html
{% extends 'base.html' %}

{% block title %}
    Roleplays
{% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Roleplays</h1>
    <p class="mb-4">Practice Cases and Submit Audio for grading by the Exec Team.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Leaderboard</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="leaderboard" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Title</th>
                            <th>Event</th>
                            <th>Link</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for case in cases %}
                            <tr>
                                <td>{{case.title}}</td>
                                <td>{{case.event}}</td>
                                <td><a href="{% url 'case' pk=case.id %}" class="btn btn-primary">Enter</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $('#leaderboard').DataTable({
            "order":[[2,"desc"]]
        });
    });
</script>
{% endblock %}