accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/edit/', views.update_profile, name='edit_profile'),
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/admin/', admin.site.urls),
    path('exam/', include('quiz.urls')),
    path('', include('accounts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('roleplay/', include('roleplay.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.index, name='quiz'),
    path('<int:num>/', views.exam, name='exam'),
    path('<int:num>/results/', views.results, name='results'),
]

quiz/models.py
from django.db import models
from django.contrib.auth.models import User
from roleplay.models import Cluster
from datetime import datetime
from django.utils import timezone

# Create your models here.
class Exam(models.Model):
    exam_number = models.IntegerField()
    exam_cluster = models.ForeignKey(Cluster, on_delete=models.PROTECT)
    def __str__(self):
        return str(self.exam_number)

class InstructionalArea(models.Model):
    title = models.CharField(max_length=100)
    def __str__(self):
        return self.title

class Question(models.Model):
    question_text = models.CharField(max_length=500)
    question_explanation = models.TextField(default="N/A")
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    instructional_area = models.ForeignKey(InstructionalArea, null=True, on_delete=models.SET_NULL)
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=250)
    is_correct = models.BooleanField()
    def __str__(self):
        return self.choice_text

class UserExam(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    is_finished = models.BooleanField(default=False)
    date = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return self.user.username + " "+ str(self.exam.exam_number)

class UserAnswer(models.Model):
    user_exam = models.ForeignKey(UserExam, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    def __str__(self):
        return self.choice.choice_text

quiz/views.py
from django.shortcuts import render, redirect
from .models import Exam
from .models import Question
from .models import Choice
from .models import UserExam
from .models import UserAnswer
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.decorators import login_required

@login_required(login_url='accounts:login')
def index(request):
    """
    Displays a list of exams tailored to a student's competitive event.
    """
    context = {}
    #get the list of exams in order of recency
    exams = Exam.objects.all()
    #only get exams relevant to the user's event if it is specified
    if request.user.profile.event is not None:
        exams = exams.filter(exam_cluster=request.user.profile.event.cluster)
    #collect exam information to display
    exams_dict = {}
    for exam in exams:
        #get all submissions this user made to this exam
        submitted_exams = UserExam.objects.filter(exam=exam, user=request.user)
        #only direct students to the most recent exam
        most_recent_exam = submitted_exams.order_by('-date').first()
        if most_recent_exam is None:
            is_finished = False
            is_started = False
        else:
            is_finished = most_recent_exam.is_finished
            is_started = True
        #determine the highest score for this exam
        high_score = 0
        for subexam in submitted_exams:
            high_score = max(high_score, subexam.score)
        exams_dict[exam] = {'is_finished': is_finished, 'is_started':is_started, 'high_score':high_score, 'most_recent_exam': most_recent_exam}
    context['exams'] = exams_dict
    #render the template
    return render(request, 'quiz/index.html', context)

@login_required(login_url='accounts:login')
def exam(request, num):
    """
    Displays all the questions of an exam
    """
    if request.method == 'POST':
        exam = Exam.objects.get(exam_number=num)
        questions = Question.objects.filter(exam=exam)
        user_exam = UserExam.objects.filter(exam=exam, user=request.user).order_by('-date').first()
        answers = UserAnswer.objects.filter(user_exam=user_exam)
        score = 0
        num_answered = 0
        for question in questions:
            if str(question.pk) in request.POST:
                try:
                    answer = answers.get(question=question)
                    answer.choice = Choice.objects.get(pk=int(request.POST[str(question.pk)]))
                except UserAnswer.DoesNotExist:
                    answer = UserAnswer(user_exam=user_exam,question=question, choice=Choice.objects.get(pk=int(request.POST[str(question.pk)])))
                finally:
                    answer.save()
                if answer.choice.is_correct:
                    score += 1
                num_answered += 1
        if num_answered == questions.count():
            user_exam.is_finished = True
            user_exam.score = score
            user_exam.date = timezone.now()
            user_exam.save()
            return redirect('quiz:results', num=exam.exam_number)
        return redirect('quiz:quiz')
    else:
        context = {}
        context['Exam'] = Exam.objects.get(exam_number=num)
        #get the userExam object that is linked with user's answers
        userExam = UserExam.objects.filter(exam=context['Exam'], user=request.user).order_by('-date').first()
        if userExam is None or userExam.is_finished:
            userExam = UserExam.objects.create(exam=context['Exam'], user=request.user)
        #put all the filled answers into a dictionary
        filled = {}
        answers = UserAnswer.objects.filter(user_exam=userExam)
        for question in Question.objects.filter(exam=context['Exam']):
            try:
                filled[question] = answers.get(question=question).choice
            except UserAnswer.DoesNotExist:
                filled[question] = None
        context['filled'] = filled
        #render exam template
        return render(request, 'quiz/exam.html', context)

@login_required(login_url='accounts:login')
def results(request, num):
    """
    Displays the results from a user's submitted exam
    """
    user_exam = UserExam.objects.filter(exam__exam_number=num, user=request.user).order_by('-date').first()
    all_answers = UserAnswer.objects.filter(user_exam=user_exam)
    correct_answers = all_answers.filter(choice__is_correct=True)
    incorrect_answers = all_answers.filter(choice__is_correct=False)
    return render(request, 'quiz/result.html', {'correct':correct_answers, 'incorrect':incorrect_answers})

quiz/templates/quiz/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>DECA Guide</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <a href="{% url 'accounts:index' %}" class="navbar-brand">DECA Guide</a> 
        <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarMenu">
            <ul class="navbar-nav">
              <li class="navbar-item">
                  <a href="{% url 'quiz:quiz' %}" class="nav-link">Exam</a>
              </li>
              <li class="navbar-nav">
                  <a href="{% url 'roleplay' %}" class="nav-link">Roleplay</a>
              </li>
              <li class="navbar-nav">
                <a href="{% url 'leaderboard' %}" class="nav-link">Leaderboard</a>
              </li>
            </ul> 
        </div>
        {% if user.is_authenticated %}
          <span class="justify-content-end" style="white-space:pre"><a href="{% url 'accounts:edit_profile' %}" style="color:white">Hello, {{user.username}}</a></span>
          <span class="justify-content-end"><a href="{% url 'accounts:logout' %}">Logout</a></span>
        {% endif %}
    </nav>
    {% block content %}
    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
  </body>
</html>

quiz/templates/quiz/exam.html
{% extends "base.html" %}
{% block content %}
<form action="" method="POST">
    {% csrf_token %}
    {% for question, answer in filled.items %}
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">#{{forloop.counter}}. {{question.question_text}}</h4>
                {% for choice in question.choice_set.all %}
                    {% if choice == answer %}
                        <input type="radio" name="{{question.id}}" id="{{choice.id}}" value="{{choice.id}}" checked>
                    {% else %}
                        <input type="radio" name="{{question.id}}" id="{{choice.id}}" value="{{choice.id}}">
                    {% endif %}
                    <label for="{{choice.id}}">{{choice.choice_text}}</label><br>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary" value="Save Progress">
</form>
{% endblock %}

quiz/templates/quiz/index.html
{% extends 'base.html' %}
{% load quiz_filter %}

{% block title %}
    Exams
{% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Multiple Choice Exams</h1>
    <p class="mb-4">Get Exams tailored to your cluster by selecting your event in the Profile section.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Exams List</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="exam_list" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Cluster</th>
                            <th>Status</th>
                            <th>High Score</th>
                            <th>Link</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for exam, examinfo in exams.items %}
                            <tr>
                                <td>{{exam.exam_number}}</td>
                                <td>{{exam.exam_cluster}}</td>
                                {% if examinfo|get_item:"is_finished" %}
                                    <td>Finished</td>
                                {% elif examinfo|get_item:"is_started" %}
                                    <td>Started</td>
                                {% else %}
                                    <td>Not Started</td>
                                {% endif %}
                                <td>{{examinfo|get_item:"high_score"}}</td>
                                <td><a href="{% url 'quiz:exam' num=exam.exam_number %}" class="btn btn-primary">Enter</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->
{% endblock %}

{% block script %}
<script>
    $(document).ready(function(){
        $('#exam_list').DataTable({
            "order":[[2,"desc"]]
        });
    });
</script>
{% endblock %}

quiz/templates/quiz/result.html
{% extends 'base.html' %}
{% block content %}
<h1>Score: {{correct.count}}</h1>
<a href="{% url 'quiz:quiz' %}">Back to List</a>
{% if incorrect.count > 0 %}
    <h1>Incorrect Answers</h1>
    {% for answer in incorrect %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">#{{forloop.counter}}. {{answer.question.question_text}}</h4>
            {% for choice in answer.question.choice_set.all %}
                {% if answer.choice == choice %}
                    <input type="radio" name="{{answer.question.id}}" id="{{choice.id}}" value="{{choice.id}}" style="color:red" disabled="disabled" checked>
                    <label for="{{choice.id}}" style="color:red">{{choice.choice_text}}</label><br>
                {% else %}
                    <input type="radio" name="{{answer.question.id}}" id="{{choice.id}}" disabled="disabled" value="{{choice.id}}">
                    {% if choice.is_correct %}
                        <label for="{{choice.id}}" style="color:limegreen">{{choice.choice_text}}</label><br>
                    {% else %}
                        <label for="{{choice.id}}">{{choice.choice_text}}</label><br>
                    {% endif %}
                {% endif %}
            {% endfor %}
        </div>
    </div>
    {% endfor %}
{% else %}
    <h1>All Correct!</h1>
{% endif %}
{% endblock %}