accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('profile/edit/', views.update_profile, name='edit_profile'),
    path('', views.index, name='index'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/admin/', admin.site.urls),
    path('exam/', include('quiz.urls')),
    path('', include('accounts.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('roleplay/', include('roleplay.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quiz/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views

app_name = 'quiz'
urlpatterns = [
    path('', views.index, name='quiz'),
    path('<int:num>/', views.exam, name='exam'),
    path('<int:num>/results/', views.results, name='results'),
]

accounts/models.py
from django.db import models
from roleplay.models import Event
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, blank=True, null=True)
    bio = models.TextField(max_length=500, blank=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, blank=True, null=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Profile
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']

class ProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-user', 'placeholder':'Bio'}))
    class Meta:
        model = Profile
        fields = ['bio', 'event']

class ChangeUserForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-user', 'placeholder':'First name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-user', 'placeholder':'Last name'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control form-control-user', 'placeholder':'Email address'}))
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-user','placeholder':'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user','placeholder':'Password'}))

class RegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control form-control-user', 'placeholder':'Username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control form-control-user','placeholder':'Email'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control form-control-user', 'placeholder':'Re-enter Password'}))
    
    class Meta:
        model = User
        fields = ['username', 'email']

accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from .forms import ProfileForm, ChangeUserForm, CreateUserForm, LoginForm, RegisterForm
from django.contrib.auth.decorators import login_required
from .models import Profile
from roleplay.models import Submission
from quiz.models import UserExam, Exam, InstructionalArea
import json
from django.db import models
from django.contrib.auth.decorators import login_required
from datetime import date

# Create your views here.
def registerPage(request):
    if request.user.is_authenticated:
        return redirect('quiz:quiz')
    else:
        form = RegisterForm()
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            print('post lol')
            if form.is_valid():
                form.save()
                return redirect('accounts:login')
            print('not success')
        context = {'form':form}
        return render(request, 'accounts/register.html', context)

def loginPage(request):
    if request.user.is_authenticated:
        return redirect('quiz:quiz')
    else:
        form = LoginForm()
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('accounts:index')
            print('failed')
        context = {'form':form}
        return render(request, 'accounts/login.html', context)

@login_required(login_url='accounts:login')
def logoutUser(request):
    logout(request)
    return redirect('accounts:login')

@login_required(login_url='accounts:login')
def update_profile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, instance=request.user.profile)
        user_form = ChangeUserForm(request.POST, instance=request.user)
        if form.is_valid() and user_form.is_valid():
            form.save()
            user_form.save()
            return redirect('quiz:quiz')
    else:
        if not hasattr(request.user, 'profile'):
            profile = Profile(user=request.user)
            profile.save()
        user_form = ChangeUserForm(instance=request.user)
        form = ProfileForm(instance=request.user.profile)
    return render(request, 'accounts/profile.html', context = {'user_form':user_form,'form':form})

@login_required(login_url='accounts:login')
def index(request):
    exams = UserExam.objects.filter(user=request.user)
    finished_exams_sorted = exams.filter(is_finished=True).order_by('date')
    titles = []
    scores = []
    for user_exam in finished_exams_sorted:
        titles.append("Exam "+str(user_exam.exam.exam_number))
        scores.append(user_exam.score)
    titles_json = json.dumps(titles)
    scores_json = json.dumps(scores)
    #calculate number of exams completed
    distinct_started = exams.values("exam").distinct().count()
    finished_exams = finished_exams_sorted.values("exam").distinct().count()
    inprogress_exams = distinct_started - finished_exams
    new_exams = Exam.objects.all().count() - distinct_started
    #calculate percentage correct
    ia_correct = {}
    instructional_areas = InstructionalArea.objects.all()
    for ia in instructional_areas:
        correct = 0
        total = 0
        for question in ia.question_set.all():
            for answer in question.useranswer_set.filter(user_exam__user=request.user):
                if answer.choice.is_correct:
                    correct+=1
                total+=1
        if total > 0:
            ia_correct[ia.title] = int(correct/total * 100)
    #determine points
    #get highest score per exam
    hi_scores = {}
    for user_exam in UserExam.objects.filter(user=request.user, is_finished=True):
        exam = user_exam.exam
        if exam in hi_scores:
            hi_scores[exam] = max(user_exam.score, hi_scores[exam])
        else:
            hi_scores[exam] = user_exam.score
    #sum up highest exam scores
    points = 0
    for score in hi_scores.values():
        points += score
    #get number of unique roleplay submissions
    subs = []
    for submission in Submission.objects.filter(student=request.user, marked=True):
        subs.append(submission.case)
    points += len(set(subs)) * 100
    return render(request, 'accounts/index.html', {'submissions': Submission.objects.filter(marked=True),'date':date.today(), 'profile':request.user.profile, 'titles':json.dumps(titles), 'scores':json.dumps(scores), 'finished_exams':json.dumps(finished_exams), 'inprogress_exams':json.dumps(inprogress_exams), 'new_exams':json.dumps(new_exams), 'ia_correct':ia_correct, 'points':points})

accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <!-- Custom fonts for this template-->
    <link href="{% static 'accounts/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'accounts/css/sb-admin-2.css' %}" rel="stylesheet">
</head>
<body class="bg-gradient-primary">

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'accounts/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'accounts/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'accounts/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'accounts/js/sb-admin-2.min.js' %}"></script>

</body>
</html>

accounts/templates/accounts/edit_profile.html
{% extends 'quiz/base.html' %}
{% block content %}
<form action='' method='POST'>
    {% csrf_token %}
    {{user_form.as_p}}
    {{form.as_p}}
    <button type='submit'>Update Changes</button>
</form>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block title %}
    Dashboard
{% endblock %}

{% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Date</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{date}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Pending Requests Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                                Event</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{profile.event}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-comments fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                                Points</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{points}}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Area Chart -->
        <div class="col-xl-8 col-lg-7">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Multiple Choice Exam Scores</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-area">
                        <canvas id="myAreaChart"></canvas>
                    </div>
                </div>
            </div>
        </div>

        <!-- Pie Chart -->
        <div class="col-xl-4 col-lg-5">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div
                    class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">MC Exam Tracker</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="chart-pie pt-4 pb-2">
                        <canvas id="myPieChart"></canvas>
                    </div>
                    <div class="mt-4 text-center small">
                        <span class="mr-2">
                            <i class="fas fa-circle text-primary"></i> Finished
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-success"></i> In Progress
                        </span>
                        <span class="mr-2">
                            <i class="fas fa-circle text-info"></i> Not Started
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Content Row -->
    <div class="row">

        <!-- Content Column -->
        <div class="col-lg-6 mb-4">
            <!-- Project Card Example -->
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Instructional Area Correct %</h6>
                </div>
                <div class="card-body">
                    {% for ia, percentage in ia_correct.items %}
                        <h4 class="small font-weight-bold">{{ia}}<span class="float-right">{{percentage}}%</span></h4>
                        <div class="progress mb-4">
                            <div class="progress-bar bg-danger" role="progressbar" style="width: {{percentage}}%"
                                aria-valuenow="{{percentage}}" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!--<div class="col-lg-6 mb-4">
            <div class="card shadow mb-4">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Illustrations</h6>
                </div>
                <div class="card-body">
                    <div class="text-center">
                        <img class="img-fluid px-3 px-sm-4 mt-3 mb-4" style="width: 25rem;"
                            src="{% static 'accounts/img/undraw_posting_photo.svg' " alt="">
                    </div>
                    <p>Add some quality, svg illustrations to your project courtesy of <a
                            target="_blank" rel="nofollow" href="https://undraw.co/">unDraw</a>, a
                        constantly updated collection of beautiful svg images that you can use
                        completely free and without attribution!</p>
                    <a target="_blank" rel="nofollow" href="https://undraw.co/">Browse Illustrations on
                        unDraw &rarr;</a>
                </div>
            </div>
        </div>-->
    </div>
</div>
<!-- /.container-fluid -->
{% endblock %}

{% block script %}
<script>
    // Set new default font family and font color to mimic Bootstrap's default styling
    Chart.defaults.global.defaultFontFamily = 'Nunito', '-apple-system,system-ui,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';
    Chart.defaults.global.defaultFontColor = '#858796';

    function number_format(number, decimals, dec_point, thousands_sep) {
    // *     example: number_format(1234.56, 2, ',', ' ');
    // *     return: '1 234,56'
    number = (number + '').replace(',', '').replace(' ', '');
    var n = !isFinite(+number) ? 0 : +number,
        prec = !isFinite(+decimals) ? 0 : Math.abs(decimals),
        sep = (typeof thousands_sep === 'undefined') ? ',' : thousands_sep,
        dec = (typeof dec_point === 'undefined') ? '.' : dec_point,
        s = '',
        toFixedFix = function(n, prec) {
        var k = Math.pow(10, prec);
        return '' + Math.round(n * k) / k;
        };
    // Fix for IE parseFloat(0.55).toFixed(0) = 0;
    s = (prec ? toFixedFix(n, prec) : '' + Math.round(n)).split('.');
    if (s[0].length > 3) {
        s[0] = s[0].replace(/\B(?=(?:\d{3})+(?!\d))/g, sep);
    }
    if ((s[1] || '').length < prec) {
        s[1] = s[1] || '';
        s[1] += new Array(prec - s[1].length + 1).join('0');
    }
    return s.join(dec);
    }

    // Area Chart Example
    var ctx = document.getElementById("myAreaChart");
    var myLineChart = new Chart(ctx, {
    type: 'line',
    data: {
        labels: {{titles|safe}},
        datasets: [{
        label: "Scores",
        lineTension: 0.3,
        backgroundColor: "rgba(78, 115, 223, 0.05)",
        borderColor: "rgba(78, 115, 223, 1)",
        pointRadius: 3,
        pointBackgroundColor: "rgba(78, 115, 223, 1)",
        pointBorderColor: "rgba(78, 115, 223, 1)",
        pointHoverRadius: 3,
        pointHoverBackgroundColor: "rgba(78, 115, 223, 1)",
        pointHoverBorderColor: "rgba(78, 115, 223, 1)",
        pointHitRadius: 10,
        pointBorderWidth: 2,
        data: {{scores|safe}},
        }],
    },
    options: {
        maintainAspectRatio: false,
        layout: {
        padding: {
            left: 10,
            right: 25,
            top: 25,
            bottom: 0
        }
        },
        scales: {
        xAxes: [{
            time: {
            unit: 'Exam'
            },
            gridLines: {
            display: false,
            drawBorder: false
            },
            ticks: {
            maxTicksLimit: 7
            }
        }],
        yAxes: [{
            ticks: {
            maxTicksLimit: 5,
            padding: 10,
            // Include a dollar sign in the ticks
            callback: function(value, index, values) {
                return number_format(value);
            }
            },
            gridLines: {
            color: "rgb(234, 236, 244)",
            zeroLineColor: "rgb(234, 236, 244)",
            drawBorder: false,
            borderDash: [2],
            zeroLineBorderDash: [2]
            }
        }],
        },
        legend: {
        display: false
        },
        tooltips: {
        backgroundColor: "rgb(255,255,255)",
        bodyFontColor: "#858796",
        titleMarginBottom: 10,
        titleFontColor: '#6e707e',
        titleFontSize: 14,
        borderColor: '#dddfeb',
        borderWidth: 1,
        xPadding: 15,
        yPadding: 15,
        displayColors: false,
        intersect: false,
        mode: 'index',
        caretPadding: 10,
        callbacks: {
            label: function(tooltipItem, chart) {
            var datasetLabel = chart.datasets[tooltipItem.datasetIndex].label || '';
            return datasetLabel + ': '+ number_format(tooltipItem.yLabel);
            }
        }
        }
    }
    });
    // Pie Chart Example
    var ctx = document.getElementById("myPieChart");
    var myPieChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
        labels: ["Finished", "In Progress", "Not Started"],
        datasets: [{
        data: [{{finished_exams|safe}}, {{inprogress_exams|safe}}, {{new_exams|safe}}],
        backgroundColor: ['#4e73df', '#1cc88a', '#36b9cc'],
        hoverBackgroundColor: ['#2e59d9', '#17a673', '#2c9faf'],
        hoverBorderColor: "rgba(234, 236, 244, 1)",
        }],
    },
    options: {
        maintainAspectRatio: false,
        tooltips: {
        backgroundColor: "rgb(255,255,255)",
        bodyFontColor: "#858796",
        borderColor: '#dddfeb',
        borderWidth: 1,
        xPadding: 15,
        yPadding: 15,
        displayColors: false,
        caretPadding: 10,
        },
        legend: {
        display: false
        },
        cutoutPercentage: 80,
    },
    });
</script>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
<!-- Outer Row -->
<div class="row justify-content-center">
    <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                    <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                    <div class="col-lg-6">
                        <div class="p-5">
                            <div class="text-center">
                                <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                            </div>
                            <form class="user" action="" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{form.username}}
                                </div>
                                <div class="form-group">
                                    {{form.password}}
                                </div>
                                <input type='submit' class="btn btn-primary btn-user btn-block" value='Login'>
                            </form>
                            <hr>
                            <!--<div class="text-center">
                                <a class="small" href="forgot-password.html">Forgot Password?</a>
                            </div>-->
                            <div class="text-center">
                                <a class="small" href="{% url 'accounts:register' %}">Create an Account!</a>
                                <br>
                                <a class="small" href="/admin/">Login as Admin</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <!--div class="card"></div>-->
    <div class="card mx-auto">
        <div class="p-5">
            <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Update Your Profile</h1>
            </div>
            <form class="user" action="" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    {{user_form.first_name}}
                </div>
                <div class="form-group">
                    {{user_form.last_name}}
                </div>
                <div class="form-group">
                    {{user_form.email}}
                </div>
                <div class="form-group">
                    {{form.bio}}
                </div>
                <div class="form-group">
                    <span>Event: </span>
                    {{form.event}}
                </div>
                <input type='submit' class="btn btn-primary btn-user btn-block" value='Update'>
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'accounts/base.html' %}

{% block title %}
    Register
{% endblock %}

{% block content %}
<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
            <div class="col-lg-7">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                    </div>
                    <form class="user" action="" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            {{form.username}}
                        </div>
                        <div class="form-group">
                            {{form.email}}
                        </div>
                        <div class="form-group row">
                            <div class="col-sm-6 mb-3 mb-sm-0">
                            {{form.password1}}
                            </div>
                            <div class="col-sm-6">
                            {{form.password2}}
                            </div>
                        </div>
                        <input type="submit" class="btn btn-primary btn-user btn-block" value="Register Account">
                    </form>
                    <hr>
                    <div class="text-center">
                        <a class="small" href="#">Forgot Password?</a>
                    </div>
                    <div class="text-center">
                        <a class="small" href="{% url 'accounts:login' %}">Already have an account? Login!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}